name: Deploy to Private Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm install

    - name: Connect to Bastion Host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BASTION_HOST }}
        username: ${{ secrets.BASTION_USERNAME }}
        key: ${{ secrets.BASTION_SSH_KEY }}
        port: 22 # SSH port of the bastion host
        args: -NL 22:${{ secrets.PRIVATE_SERVER_HOST }}:22

    - name: Deploy to Private Server
      run: ssh -p 2222 ${{ secrets.EC2_USERNAME }}@localhost "cd /var/www/html/Node-Mangod-PrivateD && git pull origin main && npm install && npm start"
