name: Deploy to EC2 in Private Subnet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH key
      uses: appleboy/ssh-action@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        script: |
          cd /var/www/html/Node-Mangod-PrivateD
          git pull origin main
          npm install
          pm2 restart Node-Mangod-PrivateD
