name: CICD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Deploy to private network via jump host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JUMP_HOST }}
          username: ${{ secrets.JUMP_USERNAME }}
          port: ${{ secrets.JUMP_PORT }}
          key: ${{ secrets.JUMP_SSH_PRIVATE_KEY }}
          script: |
            ssh -J ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} ${{ secrets.PRIVATE_USERNAME }}@${{ secrets.PRIVATE_HOST }} -p ${{ secrets.PRIVATE_PORT }} -i ${{ secrets.PRIVATE_SSH_PRIVATE_KEY }} 'cd /path/to/your/app && git pull origin main && npm install && <additional commands>'
